### ISSUE TITLE
Unable to Install asciifolders Package Due to Unsupported Engine Error

### ISSUE THREAD

**Issue by anasbehhari** [eihabkhan/asciifolders#4]
#### Description

**Issue:**
I attempted to install the `asciifolders` package using `npx asciifolders`, but encountered an error due to an unsupported engine.

**Steps to Reproduce:**
1. Run `npx asciifolders` in the terminal.
2. Confirm installation when prompted.

**Expected Behavior:**
The `asciifolders` package should be installed successfully without any errors.

**Actual Behavior:**
Encountered the following error:

```plaintext
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'asciifolders@0.0.1-beta.1',
npm WARN EBADENGINE   required: { node: '^20.9.0', pnpm: '^8.10.0' },
npm WARN EBADENGINE   current: { node: 'v18.17.0', npm: '9.6.7' }
npm WARN EBADENGINE }
Something went wrong...
[Error: ENOENT: no such file or directory, open '/Users/eihab/Developer/asciifolders/node_modules/.pnpm/figlet@1.7.0/node_modules/figlet/fonts/Big.flf'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/Users/eihab/Developer/asciifolders/node_modules/.pnpm/figlet@1.7.0/node_modules/figlet/fonts/Big.flf'
}
```
**Environment**
**Node.js version: v18.17.0**
**npm version: 9.6.7**

**Comment by eihabkhan** [comment]
Thanks for reporting the issue Anas 🫡
Should be good now, make sure to also use the LTS version of [Node](https://nodejs.org/en)
